### ISSUE TITLE
Magma 1.7.0?

### ISSUE THREAD

**Issue by diorgesl** [ShubhamTatvamasi/magma-galaxy#5]
orc8r-certifier and orc8r-nginx keep crashing:

> Events:
>   Type     Reason     Age                     From               Message
>   ----     ------     ----                    ----               -------
>   Normal   Scheduled  8m38s                   default-scheduler  Successfully assigned orc8r/orc8r-certifier-79cc56875f-7q59z to 10.13.0.217
>   Normal   Pulling    8m31s                   kubelet            Pulling image "magmacore/controller:1.7.0"
>   Normal   Pulled     6m31s                   kubelet            Successfully pulled image "magmacore/controller:1.7.0" in 1m59.30234726s
>   Normal   Created    5m55s (x4 over 6m31s)   kubelet            Created container certifier
>   Normal   Started    5m55s (x4 over 6m31s)   kubelet            Started container certifier
>   Normal   Pulled     5m12s (x4 over 6m30s)   kubelet            Container image "magmacore/controller:1.7.0" already present on machine
>   Warning  BackOff    3m27s (x24 over 6m29s)  kubelet            Back-off restarting failed container
> 

Is there anything I can do to solve this error?

**Comment by ShubhamTatvamasi** [comment]
You have to use latest helm charts.

**Comment by diorgesl** [comment]
I had to use orc8r ver 1.5.28, now is working.
