### ISSUE TITLE
Hello, how to add a new organization?

### ISSUE THREAD

**Issue by diorgesl** [ShubhamTatvamasi/magma-galaxy#9]
I tried master.magma.local, and now the master is a "organization" too.

Can you point how to access the master page?

Thank you in your good work.

**Comment by ShubhamTatvamasi** [comment]
Try: https://host.nms.magma.local

**Comment by diorgesl** [comment]
Oh nice, worked!
Thank you!

**Comment by ShubhamTatvamasi** [comment]
From host you can add one.
